name: build
on:
  push:
    tags:
      - v*
    branches:
      - main
jobs:
  release:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: "1.14.0"
      - run: make test
      - run: make build
      - uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./alfred-gcp-console-services-workflow.alfredworkflow
          asset_name: alfred-gcp-console-services-workflow.alfredworkflow
          asset_content_type: application/zip